version: '2'

services:
  bookmart:
    build: .
    environment:
      PORT: 5000
      REDIS_HOST: redis
    depends_on:
      - redis
    ports:
      - 5000:5000

  redis:
    image: redis:3.0.7-alpine
